settings:
  client:
    token: MTAzMzQ1OTE0Nzk1OTcxNzk1OA.GZmUEg.RczTqCWlb2cdibLa5LKmtCGMhwXxxMBnI9ZakA
    commands:
      commandNotFoundMessage: Cette commande n'existe pas !
  app:
    readyMessage: Bot prêt !
